SELECT --NOTAS FISCAIS LIGADAS AO PEG - COMPETÊNCIA CONTÁBIL DO PEG 07 e 08/2026
    PRE.CPFCNPJ                                  AS CPF_CNPJ,
    PRE.NOME                                     AS NOME_PRESTADOR,
    PRE.FANTASIA                                 AS NOME_FANTASIA_PRESTADOR,
    CATP.DESCRICAO                               AS CATEGORIA_PRESTADOR,
    TPP.DESCRICAO                                AS TIPO_PRESTADOR,
    DFN.NUMERONOTA                               AS NUMERO_NOTA,
    TO_CHAR(DFN.DATAEMISSAO,'DD/MM/YYYY')        AS DATA_EMISSAO,
    TO_CHAR(DFN.DATAINCLUSAO,'MM/YYYY')          AS MES_INCLUSAO,
    TO_CHAR(PG.PRIMEIRA_DATACONTABIL,'MM/YYYY')  AS MES_ANO,
    TO_CHAR(PG.ULTIMA_DATACONTABIL,'MM/YYYY')    AS MES_ANO_ULTIMO,
    PG.QTD_PEG                                   AS QTD_PEG_VINCULADOS,
    DFN.VALOR                                    AS VALOR_NOTA
FROM SAM_DOCUMENTOFISCAL_NOTA DFN
    JOIN SAM_DOCUMENTOFISCAL    DF ON DF.HANDLE = DFN.DOCUMENTOFISCAL
    JOIN SAM_AGRUPADORPAGAMENTO AP ON AP.HANDLE = DF.PAGAMENTO
    JOIN (SELECT P.AGRUPADORPAGAMENTO,
                 MIN(P.DATACONTABIL) AS PRIMEIRA_DATACONTABIL,
                 MAX(P.DATACONTABIL) AS ULTIMA_DATACONTABIL,
                 COUNT(*)            AS QTD_PEG
          FROM SAM_PEG P
          WHERE P.AGRUPADORPAGAMENTO IS NOT NULL
            AND P.DATACONTABIL >= TO_DATE('01/07/2026','DD/MM/YYYY')
            AND P.DATACONTABIL <  TO_DATE('01/09/2026','DD/MM/YYYY')
          GROUP BY P.AGRUPADORPAGAMENTO) PG ON PG.AGRUPADORPAGAMENTO = AP.HANDLE
    JOIN SAM_PRESTADOR PRE                 ON PRE.HANDLE = AP.RECEBEDOR
    LEFT JOIN SAM_CATEGORIA_PRESTADOR CATP ON CATP.HANDLE = PRE.CATEGORIA
    LEFT JOIN SAM_TIPOPRESTADOR       TPP  ON TPP.HANDLE  = PRE.TIPOPRESTADOR
ORDER BY PRE.NOME, MES_ANO
